GET http://localhost:8080/api

### 

POST http://localhost:8080/api
Content-Type: application/json

{
  "name": "Frank",
  "secret": "Has alcohol problems."
}

### 

POST http://localhost:8080/api
Content-Type: application/json

{
  "name": "Freddy",
  "secret": "Killed an elderly couple and did time."
}