### Get

GET http://localhost:8080/api/dirty-secrets

### Post 1

POST http://localhost:8080/api/dirty-secrets
Content-Type: application/json

{
  "name": "Frank",
  "secret": "Has alcohol problems."
}

### Post 2

POST http://localhost:8080/api/dirty-secrets
Content-Type: application/json

{
  "name": "Freddy",
  "secret": "Killed an elderly couple and did tiime."
}

### Put

PUT http://localhost:8080/api/dirty-secrets/id-727
Content-Type: application/json

{
  "name": "Freddy",
  "secret": "Killed an elderly couple and did time."
}

### Delete

POST http://localhost:8080/api/dirty-secrets/id-551


### Get by ID

GET http://localhost:8080/api/dirty-secrets/id-unkown